/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nego;

import BaseDatos.ConexionPostgresql;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.util.logging.Level;
import java.util.logging.Logger;


public class Nego extends javax.swing.JFrame {
    
    DefaultTableModel modelo;
    
    ConexionPostgresql postgresql = new ConexionPostgresql();
    Connection cn = postgresql.Conectar();
    
    public Nego() {
        initComponents();
        //CargarTablaClientes();
        inhabilitarCliente();
    }
    
    void inhabilitarCliente() {
        txtCedulaCliente.setEnabled(false);
        txtNombre1Cliente.setEnabled(false);
        txtNombre2Cliente.setEnabled(false);
        txtApellido1Cliente.setEnabled(false);
        txtApellido2Cliente.setEnabled(false);
        txtDireccionCliente.setEnabled(false);
        txtTelefonoCliente.setEnabled(false);
        txtCelularCliente.setEnabled(false);
        txtEmailCliente.setEnabled(false);
        
        txtCedulaCliente.setText("");
        txtNombre1Cliente.setText("");
        txtNombre2Cliente.setText("");
        txtApellido1Cliente.setText("");
        txtApellido2Cliente.setText("");
        txtDireccionCliente.setText("");
        txtTelefonoCliente.setText("");
        txtCelularCliente.setText("");
        txtEmailCliente.setText("");
                
        btnGuardarCliente.setEnabled(false);
        btnCancelarCliente.setEnabled(false);
        
    }
    
    void habilitarCliente() {
        txtCedulaCliente.setEnabled(true);
        txtNombre1Cliente.setEnabled(true);
        txtNombre2Cliente.setEnabled(true);
        txtApellido1Cliente.setEnabled(true);
        txtApellido2Cliente.setEnabled(true);
        txtDireccionCliente.setEnabled(true);
        txtTelefonoCliente.setEnabled(true);
        txtCelularCliente.setEnabled(true);
        txtEmailCliente.setEnabled(true);
        
        txtCedulaCliente.setText("");
        txtNombre1Cliente.setText("");
        txtNombre2Cliente.setText("");
        txtApellido1Cliente.setText("");
        txtApellido2Cliente.setText("");
        txtDireccionCliente.setText("");
        txtTelefonoCliente.setText("");
        txtCelularCliente.setText("");
        txtEmailCliente.setText("");
                
        btnGuardarCliente.setEnabled(true);
        btnCancelarCliente.setEnabled(true);
        
        txtCedulaCliente.requestFocus();
        
    }
    
    void CargarTablaClientes()
    {
        String[] titulos = {"ID", "Cedula", "P. Nombre", "Otros Nombre","P. Apellido", "S. Apellido",  "Direccion", "Telefono", "Celular", "E-mail"};
        String[] registro = new String[10];
        String sSQL = "";
        
        modelo = new DefaultTableModel(null, titulos);
        
        //ConexionMySQL mysql = new ConexionMySQL();
        //Connection cn = mysql.Conectar();
        
        sSQL = "SELECT * FROM clientes ";
        //       + "WHERE CONCAT(apellido1, ' ', apellido2, ' ',nombre1, ' ',nombre2) LIKE '%"+valor+"%'";
        
        try 
        {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            
            while(rs.next())
            {
                registro[0] = rs.getString("idcliente");
                registro[1] = rs.getString("cedula");
                registro[2] = rs.getString("nombre1");
                registro[3] = rs.getString("nombre2");
                registro[4] = rs.getString("apellido1");
                registro[5] = rs.getString("apellido2");
                registro[6] = rs.getString("direccion");
                registro[7] = rs.getString("telefono");
                registro[8] = rs.getString("celular");
                registro[9] = rs.getString("email");
                
                modelo.addRow(registro);
            }
            
            tblConsultaCliente.setModel(modelo);
            
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pnRegistroCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        txtNombre1Cliente = new javax.swing.JTextField();
        txtNombre2Cliente = new javax.swing.JTextField();
        txtApellido1Cliente = new javax.swing.JTextField();
        txtApellido2Cliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDireccionCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtCelularCliente = new javax.swing.JTextField();
        txtEmailCliente = new javax.swing.JTextField();
        btnNuevoCliente = new javax.swing.JButton();
        btnGuardarCliente = new javax.swing.JButton();
        btnCancelarCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultaCliente = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        pnRegistroInstructor = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCedulaInstructor = new javax.swing.JTextField();
        txtNombre1Instructor = new javax.swing.JTextField();
        txtNombre2Instructor = new javax.swing.JTextField();
        txtApellido1Instructor = new javax.swing.JTextField();
        txtApellido2Instructor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtDireccionInstructor = new javax.swing.JTextField();
        txtTelefonoInstructor = new javax.swing.JTextField();
        txtCelularInstructor = new javax.swing.JTextField();
        txtEmailInstructor = new javax.swing.JTextField();
        btnNuevoInstructor = new javax.swing.JButton();
        btnGuardarInstructor = new javax.swing.JButton();
        btnCancelarInstructor = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsultaInstructor2 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtBuscarInstructor2 = new javax.swing.JTextField();
        btnBuscarInstructor2 = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pnRegistroCliente1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtNombreServicio = new javax.swing.JTextField();
        txtValor1Servicio = new javax.swing.JTextField();
        txtValor15Servicio = new javax.swing.JTextField();
        txtValor30Servicio = new javax.swing.JTextField();
        txtValorHoraInstServicio = new javax.swing.JTextField();
        btnNuevoServicio = new javax.swing.JButton();
        btnGuardarServicio = new javax.swing.JButton();
        btnCancelarServicio = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConsultaServicio = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        txtBuscarServicio = new javax.swing.JTextField();
        btnBuscarServicio = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        pnRegistroCliente3 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtFechaClase = new javax.swing.JTextField();
        txtHoraInicioClase = new javax.swing.JTextField();
        btnNuevoClase = new javax.swing.JButton();
        btnGuardarClase = new javax.swing.JButton();
        btnCancelarClase = new javax.swing.JButton();
        cboInstructorClase = new javax.swing.JComboBox();
        cboServicioClase = new javax.swing.JComboBox();
        jPanel14 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        txtCedulaClienteClase = new javax.swing.JTextField();
        btnRegistrarClase = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblRegistrarAsistenciaClase = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblConsultaClase = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        txtBuscarClase = new javax.swing.JTextField();
        btnBuscarClase = new javax.swing.JButton();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblConsultaClase1 = new javax.swing.JTable();
        txtFechaAsistencia = new javax.swing.JTextField();
        btnBuscarClase1 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        cboInstructorAsistencia = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        txtCedulaClienteAsistencia = new javax.swing.JTextField();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        pnRegistroCliente2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtFechaInscripcion = new javax.swing.JTextField();
        txtCedulaClienteInscripcion = new javax.swing.JTextField();
        txtServicioInscripcion = new javax.swing.JTextField();
        txtFechaInicioInscripcion = new javax.swing.JTextField();
        txtFechaFinInscripcion = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtValorInscripcion = new javax.swing.JTextField();
        btnNuevoInscripcion = new javax.swing.JButton();
        btnGuardarInscripcion = new javax.swing.JButton();
        btnCancelarInscripcion = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblConsultaInscripcion = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        txtBuscarInscripcion = new javax.swing.JTextField();
        btnBuscarInscripcion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnRegistroCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Cliente"));

        jLabel1.setText("Cédula:");

        jLabel2.setText("Primer Nombre:");

        jLabel3.setText("Otros Nombres:");

        jLabel4.setText("Primer Apellido:");

        jLabel5.setText("Segundo Apellido:");

        txtCedulaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaClienteActionPerformed(evt);
            }
        });

        txtNombre1Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ClienteActionPerformed(evt);
            }
        });

        txtNombre2Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ClienteActionPerformed(evt);
            }
        });

        txtApellido1Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ClienteActionPerformed(evt);
            }
        });

        txtApellido2Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido2ClienteActionPerformed(evt);
            }
        });

        jLabel10.setText("Dirección:");

        jLabel11.setText("Teléfono:");

        jLabel12.setText("Celular:");

        jLabel13.setText("e-mail:");

        txtDireccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionClienteActionPerformed(evt);
            }
        });

        txtTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoClienteActionPerformed(evt);
            }
        });

        txtCelularCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularClienteActionPerformed(evt);
            }
        });

        txtEmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailClienteActionPerformed(evt);
            }
        });

        btnNuevoCliente.setText("Nuevo");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnGuardarCliente.setText("Guardar");
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });

        btnCancelarCliente.setText("Cancelar");
        btnCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnRegistroClienteLayout = new javax.swing.GroupLayout(pnRegistroCliente);
        pnRegistroCliente.setLayout(pnRegistroClienteLayout);
        pnRegistroClienteLayout.setHorizontalGroup(
            pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroClienteLayout.createSequentialGroup()
                .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRegistroClienteLayout.createSequentialGroup()
                        .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnRegistroClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnRegistroClienteLayout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnRegistroClienteLayout.createSequentialGroup()
                                    .addGap(124, 124, 124)
                                    .addComponent(btnNuevoCliente)
                                    .addGap(56, 56, 56)
                                    .addComponent(btnGuardarCliente))))
                        .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnRegistroClienteLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btnCancelarCliente))
                            .addGroup(pnRegistroClienteLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellido2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnRegistroClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        pnRegistroClienteLayout.setVerticalGroup(
            pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroClienteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRegistroClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevoCliente)
                            .addComponent(btnGuardarCliente)
                            .addComponent(btnCancelarCliente))
                        .addContainerGap())
                    .addGroup(pnRegistroClienteLayout.createSequentialGroup()
                        .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre1Cliente)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApellido1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtApellido2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Clientes"));

        tblConsultaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsultaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblConsultaCliente);

        jLabel6.setText("Buscar:");

        btnBuscarCliente.setText("Buscar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnBuscarCliente)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("", jPanel1);

        jTabbedPane1.addTab("Clientes", jTabbedPane2);

        pnRegistroInstructor.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Instructor"));

        jLabel7.setText("Cédula:");

        jLabel8.setText("Primer Nombre:");

        jLabel9.setText("Otros Nombres:");

        jLabel14.setText("Primer Apellido:");

        jLabel15.setText("Segundo Apellido:");

        txtCedulaInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaInstructorActionPerformed(evt);
            }
        });

        txtApellido1Instructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1InstructorActionPerformed(evt);
            }
        });

        jLabel16.setText("Dirección:");

        jLabel17.setText("Teléfono:");

        jLabel18.setText("Celular:");

        jLabel19.setText("e-mail:");

        btnNuevoInstructor.setText("Nuevo");

        btnGuardarInstructor.setText("Guardar");

        btnCancelarInstructor.setText("Cancelar");

        javax.swing.GroupLayout pnRegistroInstructorLayout = new javax.swing.GroupLayout(pnRegistroInstructor);
        pnRegistroInstructor.setLayout(pnRegistroInstructorLayout);
        pnRegistroInstructorLayout.setHorizontalGroup(
            pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroInstructorLayout.createSequentialGroup()
                .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRegistroInstructorLayout.createSequentialGroup()
                        .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnRegistroInstructorLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel7))
                            .addComponent(jLabel15)
                            .addGroup(pnRegistroInstructorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedulaInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtNombre1Instructor)
                            .addComponent(txtNombre2Instructor)
                            .addComponent(txtApellido1Instructor)
                            .addComponent(txtApellido2Instructor))
                        .addGap(59, 59, 59)
                        .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)))
                    .addGroup(pnRegistroInstructorLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnNuevoInstructor)
                        .addGap(56, 56, 56)
                        .addComponent(btnGuardarInstructor)))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarInstructor)
                    .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDireccionInstructor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(txtTelefonoInstructor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCelularInstructor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEmailInstructor, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        pnRegistroInstructorLayout.setVerticalGroup(
            pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroInstructorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedulaInstructor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel16)
                        .addComponent(txtDireccionInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRegistroInstructorLayout.createSequentialGroup()
                        .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefonoInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtCelularInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtEmailInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnRegistroInstructorLayout.createSequentialGroup()
                        .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnRegistroInstructorLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNombre1Instructor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtNombre2Instructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido1Instructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido2Instructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoInstructor)
                    .addComponent(btnGuardarInstructor)
                    .addComponent(btnCancelarInstructor))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Instructores"));

        tblConsultaInstructor2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsultaInstructor2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tblConsultaInstructor2);

        jLabel20.setText("Buscar:");

        btnBuscarInstructor2.setText("Buscar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarInstructor2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnBuscarInstructor2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtBuscarInstructor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarInstructor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnRegistroInstructor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnRegistroInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("", jPanel4);

        jTabbedPane1.addTab("Instructores", jTabbedPane3);

        pnRegistroCliente1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Servicio"));

        jLabel21.setText("Nombre del Servicio:");

        jLabel22.setText("Valor Clase:");

        jLabel23.setText("Valor Quincenal:");

        jLabel24.setText("Valor Mensual:");

        jLabel25.setText("Valor Hora Instructor:");

        txtNombreServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreServicioActionPerformed(evt);
            }
        });

        txtValor30Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor30ServicioActionPerformed(evt);
            }
        });

        btnNuevoServicio.setText("Nuevo");

        btnGuardarServicio.setText("Guardar");

        btnCancelarServicio.setText("Cancelar");

        javax.swing.GroupLayout pnRegistroCliente1Layout = new javax.swing.GroupLayout(pnRegistroCliente1);
        pnRegistroCliente1.setLayout(pnRegistroCliente1Layout);
        pnRegistroCliente1Layout.setHorizontalGroup(
            pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroCliente1Layout.createSequentialGroup()
                .addGroup(pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRegistroCliente1Layout.createSequentialGroup()
                        .addGroup(pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtValor1Servicio)
                            .addComponent(txtValor15Servicio)
                            .addComponent(txtValor30Servicio)
                            .addComponent(txtValorHoraInstServicio)))
                    .addGroup(pnRegistroCliente1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnNuevoServicio)
                        .addGap(56, 56, 56)
                        .addComponent(btnGuardarServicio)
                        .addGap(61, 61, 61)
                        .addComponent(btnCancelarServicio)))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        pnRegistroCliente1Layout.setVerticalGroup(
            pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroCliente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreServicio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor1Servicio)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor15Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(10, 10, 10)
                .addGroup(pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValor30Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorHoraInstServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoServicio)
                    .addComponent(btnGuardarServicio)
                    .addComponent(btnCancelarServicio))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Servicios"));

        tblConsultaServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsultaServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(tblConsultaServicio);

        jLabel30.setText("Buscar:");

        btnBuscarServicio.setText("Buscar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnBuscarServicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnRegistroCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnRegistroCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("", jPanel2);

        jTabbedPane1.addTab("Servicios", jTabbedPane4);

        pnRegistroCliente3.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Clase"));

        jLabel34.setText("Fecha:");

        jLabel35.setText("Instructor:");

        jLabel36.setText("Servicio:");

        jLabel37.setText("Hora Inicio:");

        txtFechaClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaClaseActionPerformed(evt);
            }
        });

        txtHoraInicioClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraInicioClaseActionPerformed(evt);
            }
        });

        btnNuevoClase.setText("Nuevo");

        btnGuardarClase.setText("Guardar");

        btnCancelarClase.setText("Cancelar");

        cboInstructorClase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboServicioClase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnRegistroCliente3Layout = new javax.swing.GroupLayout(pnRegistroCliente3);
        pnRegistroCliente3.setLayout(pnRegistroCliente3Layout);
        pnRegistroCliente3Layout.setHorizontalGroup(
            pnRegistroCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroCliente3Layout.createSequentialGroup()
                .addGroup(pnRegistroCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRegistroCliente3Layout.createSequentialGroup()
                        .addGroup(pnRegistroCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnRegistroCliente3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRegistroCliente3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnRegistroCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaClase)
                            .addComponent(txtHoraInicioClase)
                            .addComponent(cboInstructorClase, 0, 150, Short.MAX_VALUE)
                            .addComponent(cboServicioClase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnRegistroCliente3Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnNuevoClase)
                        .addGap(57, 57, 57)
                        .addComponent(btnGuardarClase)
                        .addGap(63, 63, 63)
                        .addComponent(btnCancelarClase)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        pnRegistroCliente3Layout.setVerticalGroup(
            pnRegistroCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroCliente3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRegistroCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cboInstructorClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cboServicioClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtHoraInicioClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroCliente3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoClase)
                    .addComponent(btnGuardarClase)
                    .addComponent(btnCancelarClase))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Asistencia"));

        jLabel38.setText("Cédula del Cliente:");

        btnRegistrarClase.setText("Registrar");

        tblRegistrarAsistenciaClase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane6.setViewportView(tblRegistrarAsistenciaClase);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addComponent(txtCedulaClienteClase, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnRegistrarClase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtCedulaClienteClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarClase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnRegistroCliente3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnRegistroCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Registrar", jPanel11);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Clases"));

        tblConsultaClase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsultaClase.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(tblConsultaClase);

        jLabel40.setText("Buscar:");

        btnBuscarClase.setText("Buscar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnBuscarClase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtBuscarClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarClase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane6.addTab("Consultar", jPanel12);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jTabbedPane6)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clases", jPanel10);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Asistencia"));

        tblConsultaClase1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tblConsultaClase1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane8.setViewportView(tblConsultaClase1);

        btnBuscarClase1.setText("Buscar");

        jLabel39.setText("Fecha:");

        jLabel41.setText("Instructor:");

        cboInstructorAsistencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel42.setText("Cédula del Cliente:");

        txtCedulaClienteAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaClienteAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(12, 12, 12)
                        .addComponent(txtFechaAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboInstructorAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCedulaClienteAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarClase1)
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarClase1)
                    .addComponent(jLabel39)
                    .addComponent(jLabel41)
                    .addComponent(cboInstructorAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(txtCedulaClienteAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane7.addTab("", jPanel17);

        jTabbedPane1.addTab("Asistencia", jTabbedPane7);

        pnRegistroCliente2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inscripción"));

        jLabel26.setText("Fecha:");

        jLabel27.setText("Cédula del Cliente:");

        jLabel28.setText("Servicio:");

        jLabel29.setText("Fecha Inicio:");

        jLabel31.setText("Fecha Fin:");

        txtFechaInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInscripcionActionPerformed(evt);
            }
        });

        txtServicioInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicioInscripcionActionPerformed(evt);
            }
        });

        txtFechaInicioInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicioInscripcionActionPerformed(evt);
            }
        });

        jLabel32.setText("Valor:");

        btnNuevoInscripcion.setText("Nuevo");

        btnGuardarInscripcion.setText("Guardar");

        btnCancelarInscripcion.setText("Cancelar");

        javax.swing.GroupLayout pnRegistroCliente2Layout = new javax.swing.GroupLayout(pnRegistroCliente2);
        pnRegistroCliente2.setLayout(pnRegistroCliente2Layout);
        pnRegistroCliente2Layout.setHorizontalGroup(
            pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroCliente2Layout.createSequentialGroup()
                .addGroup(pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRegistroCliente2Layout.createSequentialGroup()
                        .addGroup(pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnRegistroCliente2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRegistroCliente2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaInscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtCedulaClienteInscripcion)
                            .addComponent(txtServicioInscripcion)
                            .addComponent(txtFechaInicioInscripcion)
                            .addComponent(txtFechaFinInscripcion)
                            .addComponent(txtValorInscripcion)))
                    .addGroup(pnRegistroCliente2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnNuevoInscripcion)
                        .addGap(58, 58, 58)
                        .addComponent(btnGuardarInscripcion)
                        .addGap(57, 57, 57)
                        .addComponent(btnCancelarInscripcion)))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        pnRegistroCliente2Layout.setVerticalGroup(
            pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistroCliente2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtCedulaClienteInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtServicioInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtFechaInicioInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtFechaFinInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtValorInscripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnRegistroCliente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoInscripcion)
                    .addComponent(btnGuardarInscripcion)
                    .addComponent(btnCancelarInscripcion))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRegistroCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnRegistroCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Inscribir", jPanel7);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Inscripciones"));

        tblConsultaInscripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsultaInscripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(tblConsultaInscripcion);

        jLabel33.setText("Buscar:");

        btnBuscarInscripcion.setText("Buscar");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnBuscarInscripcion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtBuscarInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarInscripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Consultar", jPanel8);

        jTabbedPane1.addTab("Inscripciones", jTabbedPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValor30ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor30ServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor30ServicioActionPerformed

    private void txtNombreServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreServicioActionPerformed

    private void txtApellido1InstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1InstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1InstructorActionPerformed

    private void txtCedulaInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaInstructorActionPerformed

    private void txtApellido1ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ClienteActionPerformed
        txtApellido1Cliente.transferFocus();
    }//GEN-LAST:event_txtApellido1ClienteActionPerformed

    private void txtCedulaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaClienteActionPerformed
        txtCedulaCliente.transferFocus();
    }//GEN-LAST:event_txtCedulaClienteActionPerformed

    private void txtFechaInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInscripcionActionPerformed

    private void txtFechaInicioInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioInscripcionActionPerformed

    private void txtServicioInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicioInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicioInscripcionActionPerformed

    private void txtFechaClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaClaseActionPerformed

    private void txtHoraInicioClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraInicioClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraInicioClaseActionPerformed

    private void txtCedulaClienteAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaClienteAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaClienteAsistenciaActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        habilitarCliente();
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClienteActionPerformed
        inhabilitarCliente();
    }//GEN-LAST:event_btnCancelarClienteActionPerformed

    private void txtNombre1ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ClienteActionPerformed
        txtNombre1Cliente.transferFocus();
    }//GEN-LAST:event_txtNombre1ClienteActionPerformed

    private void txtNombre2ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ClienteActionPerformed
        txtNombre2Cliente.transferFocus();
    }//GEN-LAST:event_txtNombre2ClienteActionPerformed

    private void txtApellido2ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido2ClienteActionPerformed
        txtApellido2Cliente.transferFocus();
    }//GEN-LAST:event_txtApellido2ClienteActionPerformed

    private void txtDireccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionClienteActionPerformed
        txtDireccionCliente.transferFocus();
    }//GEN-LAST:event_txtDireccionClienteActionPerformed

    private void txtTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoClienteActionPerformed
        txtTelefonoCliente.transferFocus();
    }//GEN-LAST:event_txtTelefonoClienteActionPerformed

    private void txtCelularClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularClienteActionPerformed
        txtCelularCliente.transferFocus();
    }//GEN-LAST:event_txtCelularClienteActionPerformed

    private void txtEmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailClienteActionPerformed
        //txtEmailCliente.transferFocus();
    }//GEN-LAST:event_txtEmailClienteActionPerformed

    
    String accionClientes = "Insertar";
    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        
        String ced, nom1, nom2, ap1, ap2, dir, tel, cel, email;
        String sSQL = "";
        String mensaje = "";
        
        ced = txtCedulaCliente.getText();
        nom1 = txtNombre1Cliente.getText();
        nom2 = txtNombre2Cliente.getText();
        ap1 = txtApellido1Cliente.getText();
        ap2 = txtApellido2Cliente.getText();
        dir = txtDireccionCliente.getText();
        tel = txtTelefonoCliente.getText();
        cel = txtCelularCliente.getText();
        email = txtEmailCliente.getText();
        
        if(accionClientes.equals("Insertar"))
        {            
            sSQL = "INSERT INTO clientes(cedula, nombre1, nombre2, apellido1, apellido2, direccion, telefono, celular, email)"
                    + "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            mensaje = "Los datos se han Insertado";
        }
        else if(accionClientes.equals("Modificar"))
        {
            /*sSQL = "UPDATE datos_personales "
                    + "SET apellido1 = ?,"
                    + "apellido2 = ?,"
                    + "nombre1 = ?,"
                    + "nombre2 = ?,"
                    + "fecha_nac = ?,"
                    + "genero = ? "
                    + "WHERE id_emp = "+id_actualizar;
                               
            mensaje = "Los datos se han Modificado"; */
        }
        
        try
        {
            PreparedStatement pst = cn.prepareStatement(sSQL);
            pst.setString(1, ced);
            pst.setString(2, nom1);
            pst.setString(3, nom2);
            pst.setString(4, ap1);
            pst.setString(5, ap2);
            pst.setString(6, dir);
            pst.setString(7, tel);
            pst.setString(8, cel);
            pst.setString(9, email);
            
            inhabilitarCliente();  //Marian
            
            int n = pst.executeUpdate();
            
            if (n > 0)
            {
                JOptionPane.showMessageDialog(null, mensaje);
                CargarTablaClientes();
            }
            
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /*
        String sSQL = "";
        
        sSQL = "INSERT INTO cursos(idcurso, codcurso, valorcurso, valorhorainst, mensualidad)"
                + "VALUES(?, ?, ?, ?, ?, ?)";
        
        try
        {
            PreparedStatement pst = cn.prepareStatement(sSQL);
            pst.setString(1, 3);
            pst.setString(2, '1');
            pst.setString(3, '2');
            pst.setString(4, '2');
            pst.setString(5, '3');
            pst.setString(6, '4');
            
            int n = pst.executeUpdate();
            
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nego().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarClase;
    private javax.swing.JButton btnBuscarClase1;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarInscripcion;
    private javax.swing.JButton btnBuscarInstructor2;
    private javax.swing.JButton btnBuscarServicio;
    private javax.swing.JButton btnCancelarClase;
    private javax.swing.JButton btnCancelarCliente;
    private javax.swing.JButton btnCancelarInscripcion;
    private javax.swing.JButton btnCancelarInstructor;
    private javax.swing.JButton btnCancelarServicio;
    private javax.swing.JButton btnGuardarClase;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JButton btnGuardarInscripcion;
    private javax.swing.JButton btnGuardarInstructor;
    private javax.swing.JButton btnGuardarServicio;
    private javax.swing.JButton btnNuevoClase;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNuevoInscripcion;
    private javax.swing.JButton btnNuevoInstructor;
    private javax.swing.JButton btnNuevoServicio;
    private javax.swing.JButton btnRegistrarClase;
    private javax.swing.JComboBox cboInstructorAsistencia;
    private javax.swing.JComboBox cboInstructorClase;
    private javax.swing.JComboBox cboServicioClase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JPanel pnRegistroCliente;
    private javax.swing.JPanel pnRegistroCliente1;
    private javax.swing.JPanel pnRegistroCliente2;
    private javax.swing.JPanel pnRegistroCliente3;
    private javax.swing.JPanel pnRegistroInstructor;
    private javax.swing.JTable tblConsultaClase;
    private javax.swing.JTable tblConsultaClase1;
    private javax.swing.JTable tblConsultaCliente;
    private javax.swing.JTable tblConsultaInscripcion;
    private javax.swing.JTable tblConsultaInstructor2;
    private javax.swing.JTable tblConsultaServicio;
    private javax.swing.JTable tblRegistrarAsistenciaClase;
    private javax.swing.JTextField txtApellido1Cliente;
    private javax.swing.JTextField txtApellido1Instructor;
    private javax.swing.JTextField txtApellido2Cliente;
    private javax.swing.JTextField txtApellido2Instructor;
    private javax.swing.JTextField txtBuscarClase;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtBuscarInscripcion;
    private javax.swing.JTextField txtBuscarInstructor2;
    private javax.swing.JTextField txtBuscarServicio;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCedulaClienteAsistencia;
    private javax.swing.JTextField txtCedulaClienteClase;
    private javax.swing.JTextField txtCedulaClienteInscripcion;
    private javax.swing.JTextField txtCedulaInstructor;
    private javax.swing.JTextField txtCelularCliente;
    private javax.swing.JTextField txtCelularInstructor;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtDireccionInstructor;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEmailInstructor;
    private javax.swing.JTextField txtFechaAsistencia;
    private javax.swing.JTextField txtFechaClase;
    private javax.swing.JTextField txtFechaFinInscripcion;
    private javax.swing.JTextField txtFechaInicioInscripcion;
    private javax.swing.JTextField txtFechaInscripcion;
    private javax.swing.JTextField txtHoraInicioClase;
    private javax.swing.JTextField txtNombre1Cliente;
    private javax.swing.JTextField txtNombre1Instructor;
    private javax.swing.JTextField txtNombre2Cliente;
    private javax.swing.JTextField txtNombre2Instructor;
    private javax.swing.JTextField txtNombreServicio;
    private javax.swing.JTextField txtServicioInscripcion;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTelefonoInstructor;
    private javax.swing.JTextField txtValor15Servicio;
    private javax.swing.JTextField txtValor1Servicio;
    private javax.swing.JTextField txtValor30Servicio;
    private javax.swing.JTextField txtValorHoraInstServicio;
    private javax.swing.JTextField txtValorInscripcion;
    // End of variables declaration//GEN-END:variables
}
